### ISSUE TITLE
Update DNS entry for openscanhub.dev

### ISSUE THREAD

**Issue by siteshwar** [openscanhub/openscanhub.github.io#2]
We have a homepage on [GitHub pages](https://openscanhub.github.io/). DNS entry for `openscanhub.dev` should be [updated](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages) to point to it.

**Comment by kdudka** [comment]
I have requested update of the DNS records with the following (internal) SN ticket: https://redhat.service-now.com/help?id=rh_ticket&table=sc_req_item&sys_id=b3281d5297a479102f8d361e6253af05

**Comment by siteshwar** [comment]
DNS records have been updated and https://openscanhub.dev/ is now accessible. So I am closing this issue.
